package com.manoj.myWebApp.model;

import org.springframework.stereotype.Component;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

// import lombok.AllArgsConstructor;
// import lombok.Data;


// Generated by Spring Boot Data JPA (Domain Object)
// @Data is used to generate getters and setters for the fields of the class
// @AllArgsConstuctor is used to generate a constructor that takes all the fields of the class as arguments
// @Entity is used to indicate that this class is a JPA entity handled by hibernate

// @Data
// @AllArgsConstructor
@Component
@Entity
public class Product {
    

    // To declare prodId as the primary key of the Product table
    @Id
    private int prodId;
    private String prodName;
    private int price;

    // Using lombok library instead of Constructor or getters, setters for declaring private var's

    // OR using get,set, Const

    public Product(){};

    public Product(int prodId, String prodName, int price){
        this.prodId = prodId;
        this.prodName = prodName;
        this.price = price;
    }


    public int getProdId(){return prodId;}
    public String getProdName(){return prodName;}
    public int getPrice(){return price;}

    public void setProdId(int prodId){this.prodId=prodId;}

    @Override
    public String toString() {
        return "Product {prodId=" + prodId + ", prodName=" + prodName + ", price=" + price + "}";
    }
 
    

}
